services:
  - type: web
    name: smart-ai-backend
    env: python
    buildCommand: |
      apt-get update
      apt-get install -y tesseract-ocr
      apt-get install -y tesseract-ocr-ara
      apt-get install -y tesseract-ocr-eng
      apt-get install -y poppler-utils
      pip install -r requirements.txt
    startCommand: bash start.sh